# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  playwright-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.22.0-focal
    working_directory: ~/circleci-demo-workflows
    environment:
      NODE_ENV: development
    steps:
      - add_ssh_keys:
          fingerprints:
            - "d6:36:58:af:d8:57:47:db:30:77:62:ea:40:f7:03:03"
      - checkout
      - run: npm install
      - run: npm install -g docker 
      - run: docker exec -u root -t -i container_id /bin/bash
      - run:
          name: Install Java
          command: |
           apt-get update 
           apt-get -y install sudo
           sudo apt install openjdk-8-jdk -y
           export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
           export PATH=$PATH:$JAVA_HOME/bin
      - run: 
          name: Install Playwright
          command: |
           npm i -D playwright @playwright/test
           npm i -D experimental-allure-playwright 
      - run:
          name: Install Allure
          command: npm i -D allure-commandline
      - run: 
          name: Generate Allure report
          command: |
           npx playwright test --reporter=experimental-allure-playwright ||true
           npx allure generate ./allure-results --clean
      - run:
          docker save -o < ~/circleci-demo-workflows/image mcr.microsoft.com/playwright:v1.22.0-focal
      - persist_to_workspace:
          root: .
          paths: [~/circleci-demo-workflows/image]
  
  publish-report:
    docker:
      - image: mcr.microsoft.com/playwright:v1.22.0-focal
    steps:   
      - attach_workspace:
          at: ~/circleci-workspace
      - run: docker load -i ~/circleci-workspace/image
      - run:
          name: Install Github Pages
          command: npm install gh-pages -g
      - run:
          name: Publish report to Github Pages
          command: |
            git config user.email "anne.h@mailfence.com"
            git config user.name "anneH"
            gh-pages --dist ./allure-report

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  e2e-test-workflow:
    jobs:
      - playwright-test
      - publish-report
